services:
  backend:
    image: credo7/docker-project-sem2-backend:latest
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          cpus: 0.5
          memory: 512M

  frontend:
    depends_on:
      backend:
        condition: service_healthy
    image: credo7/docker-project-sem2-frontend:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/momo-store.conf:ro
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_BACKEND_ADDRESS: http://backend:8081/
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - frontend
      - backend
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 256M

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true