version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: credo7/docker-project-sem2-backend:latest
    container_name: momo-store-be
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - momo-net
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    healthcheck:
      # Using curl is generally more robust for healthchecks.
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          cpus: '0.25'
          memory: 256M
    tmpfs:
      - /tmp
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: credo7/docker-project-sem2-frontend:latest
    container_name: momo-store-fe
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "80:80"
    networks:
      - momo-net
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.3'
    read_only: true
    volumes:
      - nginx-cache:/var/cache/nginx
      - nginx-pid:/var/run

networks:
  momo-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: momo-bridge

volumes:
  backend_data:
    driver: local
  nginx-cache:
  nginx-pid:
